
export const CREATE_POSTS = 'POST/CREATE_POST';
export const CREATE_POSTS_FULFILLED = 'POST/CREATE_POST/FULFILED';
export const CREATE_POSTS_REJECTED = 'POST/CREATE_POST/REJECTED';


export const GET_UNICORNS = 'POST/UNICORNS';
export const GET_UNICORNS_FULFILED = 'POST/UNICORNS/FULFILED';
export const GET_UNICORNS_REJECTED = 'POST/UNICORNS/REJECTED';

export const DELETE_UNICORN = 'POST/DELETE';
export const DELETE_UNICORN_FULFILED = 'POST/DELETE/FULFILED';
export const DELETE_UNICORN_REJECTED = 'POST/DELETE/REJECTED';

export const UPDATE_UNICORNS = 'POST/UPDATE';
export const UPDATE_UNICORNS_FULFILED = 'POST/UPDATE/FULFILED';
export const UPDATE_UNICORNS_REJECTED = 'POST/UPDATE/REJECTED';

export const HANDLE_ERORS = 'SYSTEM/ERROR';
